### ISSUE TITLE
Please publish Akka.Persistence.MySql.1.1.0-Beta to Nuget

### ISSUE THREAD

**Issue by CFMITL** [akkadotnet/Akka.Persistence.MySql#11]
I am having problems with using the 1.0.0 version of this module because of changes to signatures.  

I discovered the latest changes were not pushed to Nuget: See https://www.nuget.org/packages/Akka.Persistence.MySql/

Please publish this to Nuget.  Is there something I can do to help?

**Comment by joshgarnett** [comment]
*bump* this would be really useful to have

**Comment by alexvaluyskiy** [comment]
Akka.Persistence.MySql.1.1.0-Beta is never exists. You could try to use the latest version from nightly builds: https://www.myget.org/feed/akkadotnet-contrib/package/nuget/Akka.Persistence.MySql
